pipeline {


agent {
    label 'jenkins-agent'
}

stages {

    stage('Checkout') {
        steps {
            git branch: 'main',
                credentialsId: 'github-ssh',
                url: 'git@github.com:sidharth-sehrawat/ELK-project.git'
        }
    }

    stage('SonarQube Analysis') {
        steps {
            withSonarQubeEnv('sonarqube') {
                sh '''
                sonar-scanner \
                -Dsonar.projectKey=ELK-project \
                -Dsonar.projectName=ELK-project \
                -Dsonar.sources=. \
                -Dsonar.token=$SONAR_AUTH_TOKEN
                '''
            }
        }
    }

    stage('Trivy Scan') {
        steps {
            sh '''
            trivy fs . \
            --severity HIGH,CRITICAL \
            --no-progress
            '''
        }
    }

    stage('Deploy') {
        steps {
            sh '''
            kubectl rollout restart deployment/mario-app -n default

            kubectl rollout status deployment/mario-app \
            -n default \
            --timeout=300s
            '''
        }
    }

    stage('Verification') {
        steps {
            sh '''
            kubectl get pods -n default
            kubectl get svc -n default
            kubectl get ingress -n default
            '''
        }
    }
}

post {

    success {
        echo 'Pipeline completed successfully'
    }

    failure {
        echo 'Pipeline failed'
    }
}


}

